[languageConf.cpp]
SourceName = 'source.cpp'
ArtifactName = 'a.out'
Compiler = '/usr/bin/g++'
CompileCmd = "$Compiler $Args ${SourceName} -o ${ArtifactName}"
CompileTimeLimit = 20000 # ms
CompileSpaceLimit = 104857600
ExecuteCmd = "a.out"
Options = { o2 = "-O2", cpp14 = "--std=c++14" }

[languageConf.c]
SourceName = 'source.c'
ArtifactName = 'a.out'
Compiler = '/usr/bin/gcc'
CompileCmd = "$Compiler $Args ${SourceName} -o ${ArtifactName}"
CompileTimeLimit = 10000 # ms
CompileSpaceLimit = 104857600
ExecuteCmd = "a.out"

[languageConf.java]
SourceName = 'Source.java'
ArtifactName = 'Source.class'
Environment = [ "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" ]
Compiler = '$JAVA_HOME/bin/javac'
CompileCmd = "$Compiler $Args $SourceName"
CompileTimeLimit = 20000 # ms
CompileSpaceLimit = 104857600
ExecuteCmd = "$JAVA_HOME/bin/java -jar $ArtifactName"
Options = { "java11" = "--source 11", "java8" = "--source 8" }